/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrew Hyun
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class changePassword extends javax.swing.JDialog {

    /**
     * Creates new form changePassword
     */
    
    //declare variables
    String currentPassword, newPassword, confirmNewPassword;
    private boolean visible = false;
    private boolean newPassMatch = false;
    Connection con;
    Statement stmt;
    ResultSet rs;
    
    
    
    public changePassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    //Constructor of Dialog
    changePassword(java.awt.Dialog parent, boolean modal, Connection con, Statement stmt, ResultSet rs) {
        super(parent, modal);
        initComponents();
        
        //initialize variables
        visible = true;
        this.con = con;
        this.stmt = stmt;
        this.rs = rs;
        newPassMatch = false;
        
        initFcn();
    }

    private void initFcn(){
        if(visible == true){
            this.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOkay = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        confirmNewPass = new javax.swing.JPasswordField();
        currPass = new javax.swing.JPasswordField();
        newPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOkay.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        btnOkay.setText("OK");
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });
        getContentPane().add(btnOkay, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 70));

        btnCancel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, 70));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Current Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Confirm New Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 20));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("New Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 100, 20));

        confirmNewPass.setText("aaaaaaaaaaaaaaa");
        confirmNewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmNewPassFocusGained(evt);
            }
        });
        confirmNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmNewPassKeyReleased(evt);
            }
        });
        getContentPane().add(confirmNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 180, -1));

        currPass.setText("aaaaaaaaaaaaaaa");
        currPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                currPassFocusGained(evt);
            }
        });
        currPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                currPassKeyReleased(evt);
            }
        });
        getContentPane().add(currPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 180, -1));

        newPass.setText("aaaaaaaaaaaaaaa");
        newPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPassFocusGained(evt);
            }
        });
        newPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newPassKeyReleased(evt);
            }
        });
        getContentPane().add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 180, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Change This Account's Password:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Menu Template/Background/backgroundPic400x300.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
        //if button is pushed, check if passwords match else send error message
        try{
        if(newPassMatch == true){
            if(currentPassword.equals(rs.getString("password"))){
                rs.updateString("password", newPassword);
                rs.updateRow();
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(this, "You have entered the incorrect password (Confirm Password)");
        }
        else 
            JOptionPane.showMessageDialog(this, "The passwords you have entered "
                    + "do not match.\n Please double check the new Password fields.");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnOkayActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void currPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currPassFocusGained
        if(String.valueOf(currPass.getPassword()).equals("aaaaaaaaaaaaaaa"))
            currPass.setText("");
    }//GEN-LAST:event_currPassFocusGained

    private void newPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPassFocusGained
        if(String.valueOf(newPass.getPassword()).equals("aaaaaaaaaaaaaaa"))
            newPass.setText("");
    }//GEN-LAST:event_newPassFocusGained

    private void confirmNewPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmNewPassFocusGained
        if(String.valueOf(confirmNewPass.getPassword()).equals("aaaaaaaaaaaaaaa"))
            confirmNewPass.setText("");
    }//GEN-LAST:event_confirmNewPassFocusGained

    private void currPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currPassKeyReleased
        //anything typed in the 'current password' field box will be stored in this variable
        currentPassword = String.valueOf(currPass.getPassword());
    }//GEN-LAST:event_currPassKeyReleased

    private void newPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPassKeyReleased
        //anything typed in the 'current password' field box will be stored in this variable
        newPassword = String.valueOf(newPass.getPassword());
        //check if the password typed in the new password fields match
        if(newPassword.equals(confirmNewPassword))
            newPassMatch = true;
        else
            newPassMatch = false;
    }//GEN-LAST:event_newPassKeyReleased

    private void confirmNewPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmNewPassKeyReleased
        //anything typed in the 'current password' field box will be stored in this variable
        confirmNewPassword = String.valueOf(confirmNewPass.getPassword());
        //check if the password typed in the new password fields match
        if(newPassword.equals(confirmNewPassword))
            newPassMatch = true;
        else
            newPassMatch = false;
    }//GEN-LAST:event_confirmNewPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                changePassword dialog = new changePassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOkay;
    private javax.swing.JPasswordField confirmNewPass;
    private javax.swing.JPasswordField currPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField newPass;
    // End of variables declaration//GEN-END:variables
}
