
/**
 *
 * @author Andrew Hyun
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Fire_Employee extends javax.swing.JDialog {

    /**
     * Creates new form Fire_Employee
     */
    //Class variables
    private int id;
    Connection con;
    Statement stmt;
    ResultSet rs;
    String adminPass;
    public static boolean firebtnpress = false;
    
    public Fire_Employee(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    //constructor used
    Fire_Employee(java.awt.Dialog parent, boolean modal, int selectedID) {
        super(parent, modal);
        initComponents();
        id = selectedID;
        firebtnpress = false;
        try{
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Project1",
                    "username", "password");
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("Select * from username.users");
            rs.absolute(1);
            adminPass = rs.getString("Password");
            rs.beforeFirst();
            while(rs.next()){
                if(rs.getInt("id") == selectedID)
                    break;
            }
            labelSelectedID.setText(rs.getString("First_Name") + " " + rs.getString("Last_Name"));
            
            rs.close();
            stmt.close();
            
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("Select * from username.employees");
            while(rs.next()){
                if(rs.getInt("Employee_ID") == selectedID)
                    break;
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }    
        visible();
    }

    private void visible(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSelectedID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        passAdmin = new javax.swing.JPasswordField();
        btnOkay = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSelectedID.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        labelSelectedID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelSelectedID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("to Continue.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 380, 30));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please Enter 'ADMIN' Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 380, 30));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("You are about to FIRE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 30));

        passAdmin.setText("aaaaaaaaaaaaaaaaaaaa");
        passAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passAdminFocusGained(evt);
            }
        });
        getContentPane().add(passAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        btnOkay.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        btnOkay.setText("OK");
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });
        getContentPane().add(btnOkay, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 70));

        btnCancel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Menu Template/Background/backgroundPic400x300.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passAdminFocusGained
        if(String.valueOf(passAdmin.getPassword()).equals("aaaaaaaaaaaaaaaaaaaa"))
            passAdmin.setText("");
    }//GEN-LAST:event_passAdminFocusGained

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            //When cancel button is pushed dispose this dialog           
            rs.close();
            stmt.close();
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
        //When okay button is pushed check if password is correct AND that they match
        try{
            
            if(String.valueOf(passAdmin.getPassword()).equals(adminPass)){
                    rs.updateBoolean("New_Message_Fired", true);
                    rs.updateBoolean("New_Message_Promote", false);
                    rs.updateBoolean("New_Message_Demote", false);
                    firebtnpress = true;
                    rs.close();
                    stmt.close();
                    this.dispose();
                }
            else{
                    JOptionPane.showMessageDialog(this, "Incorrect Password entered.");
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnOkayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fire_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fire_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fire_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fire_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Fire_Employee dialog = new Fire_Employee(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOkay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelSelectedID;
    private javax.swing.JPasswordField passAdmin;
    // End of variables declaration//GEN-END:variables
}
