/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrew Hyun
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Promote_Demote extends javax.swing.JDialog {

    /**
     * Creates new form Promote_Demote
     */
    private int selectedID;
    Connection con;
    Statement stmt;
    ResultSet rs;
    
    public Promote_Demote(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    //Constructor used
    public Promote_Demote(java.awt.Dialog parent, boolean modal, int id){
        super(parent, modal);
        initComponents();
        selectedID = id;
        try{
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Project1",
                    "username", "password");
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("Select * from username.users");
            while(rs.next()){
                if(rs.getInt("id") == selectedID)
                    break;
            }
            labelSelectedID.setText(rs.getString("First_Name") + " " + rs.getString("Last_Name"));
            
            rs.close();
            stmt.close();
            
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("Select * from username.employees");
            while(rs.next()){
                if(rs.getInt("Employee_ID") == selectedID)
                    break;
            }
            if(rs.getString("Job_Type") != null)
                textCurrJob.setText(rs.getString("Job_Type"));
            else
                textCurrJob.setText("Not set.");
            if(rs.getString("Salary") != null)
                textCurrSalary.setText("$" + rs.getDouble("Salary"));
            else
                textCurrSalary.setText("Not Set.");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }    
        visible();
    }

    private void visible(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSelectedID = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        labelCurrJob = new javax.swing.JLabel();
        textCurrJob = new javax.swing.JTextField();
        labelNewJob = new javax.swing.JLabel();
        textNewJob = new javax.swing.JTextField();
        labelCurrSalary = new javax.swing.JLabel();
        textCurrSalary = new javax.swing.JTextField();
        labelNewSalary = new javax.swing.JLabel();
        textNewSalary = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSelectedID.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        labelSelectedID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelSelectedID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 30));

        btnCancel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 210, 150, 70));

        btnChange.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 210, 150, 70));

        labelCurrJob.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelCurrJob.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCurrJob.setText("Current Job");
        getContentPane().add(labelCurrJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, 20));

        textCurrJob.setEnabled(false);
        getContentPane().add(textCurrJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 170, -1));

        labelNewJob.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelNewJob.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNewJob.setText("New Job Title");
        getContentPane().add(labelNewJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 100, 20));
        getContentPane().add(textNewJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, -1));

        labelCurrSalary.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelCurrSalary.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCurrSalary.setText("Current Salary");
        getContentPane().add(labelCurrSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 100, 20));

        textCurrSalary.setEnabled(false);
        getContentPane().add(textCurrSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, -1));

        labelNewSalary.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelNewSalary.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNewSalary.setText("New Salary");
        getContentPane().add(labelNewSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 80, 20));
        getContentPane().add(textNewSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("You chose to PROMOTE/DEMOTE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Menu Template/Background/backgroundPic400x300.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        try{
            rs.updateString("Job_Type", textNewJob.getText());
            Double currSalary, newSalary;
            boolean isDouble;
            
            if(textCurrSalary.getText().equals("Not Set") || textCurrSalary.getText().equals("Not Set."))
                currSalary = (double)0;
            else
                currSalary = Double.parseDouble(textCurrSalary.getText().substring(1));
            if(textNewSalary.getText().contains("$")){
                newSalary = Double.parseDouble(textNewSalary.getText().substring(1));
                if(newSalary.toString().matches("^[0-9]*\\.?[0-9]*$")){
                    isDouble = true;
                    rs.updateDouble("Salary", newSalary);
                }
                else{
                    JOptionPane.showMessageDialog(this, "The new salary entered is in an incorrect format.");
                    isDouble = false;
                }
            }
            else{
                newSalary = Double.parseDouble(textNewSalary.getText());
                if(newSalary.toString().matches("^[0-9]*\\.?[0-9]*$")){
                    rs.updateDouble("Salary", newSalary);
                    isDouble = true;
                }
                else{
                    JOptionPane.showMessageDialog(this, "The new salary entered is in an incorrect format.");
                    isDouble = false;
                }
            }
            
            if(isDouble == true){
                if(newSalary >= currSalary){
                    rs.updateBoolean("New_Message_Promote", true);
                    rs.updateBoolean("New_Message_Demote", false);
                }
                else if(newSalary < currSalary){
                    rs.updateBoolean("New_Message_Demote", true);
                    rs.updateBoolean("New_Message_Promote", false);
                }
            }
            rs.updateRow();
            
            rs.close();
            stmt.close();
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            rs.close();
            stmt.close();
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promote_Demote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promote_Demote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promote_Demote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promote_Demote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Promote_Demote dialog = new Promote_Demote(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCurrJob;
    private javax.swing.JLabel labelCurrSalary;
    private javax.swing.JLabel labelNewJob;
    private javax.swing.JLabel labelNewSalary;
    private javax.swing.JLabel labelSelectedID;
    private javax.swing.JTextField textCurrJob;
    private javax.swing.JTextField textCurrSalary;
    private javax.swing.JTextField textNewJob;
    private javax.swing.JTextField textNewSalary;
    // End of variables declaration//GEN-END:variables
}
