
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrew Hyun
 */
public class Terminate extends javax.swing.JDialog {

    /**
     * Creates new form Terminate
     */
    
    //declare variables and set equal to false in case they were pre-maturely called
    public static boolean passwordMatch = false;
    public static boolean terminateAcc = false;
    Connection con;
    Statement stmt;
    ResultSet rs;
    String passwordEntered, confirmedPassword;
    private boolean visible = false;

    Terminate(java.awt.Frame parent, boolean modal){
        super(parent, modal);
        initComponents();
    }
    
    //Constructor of this dialog
    Terminate(java.awt.Dialog parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        //set variables as false if dialog is created
        passwordMatch = false;
        terminateAcc = false;
        visible = true;
        
        //get the rs.absolute id and store it
        try{
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Project1", "username", "password");
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery("Select * from Username.users");
            rs.absolute(id);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
        //setVisible to true
        initFcn();
    }

    private void initFcn(){
        if(visible == true)
            this.setVisible(true);
        else
            this.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passField = new javax.swing.JPasswordField();
        confirmPassField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnOkay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passField.setText("aaaaaaaaaaaaaaa");
        passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFieldFocusGained(evt);
            }
        });
        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passFieldKeyReleased(evt);
            }
        });
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 180, -1));

        confirmPassField.setText("aaaaaaaaaaaaaaa");
        confirmPassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPassFieldFocusGained(evt);
            }
        });
        confirmPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmPassFieldKeyReleased(evt);
            }
        });
        getContentPane().add(confirmPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, 20));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 80, 20));

        btnCancel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, 70));

        btnOkay.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        btnOkay.setText("OK");
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });
        getContentPane().add(btnOkay, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 70));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("To TERMINATE your account, please");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 30));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("type your password below and hit");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("the \"OK\" button");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 380, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Menu Template/Background/backgroundPic400x300.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        try {
            //When cancel button is pushed set terminateAcc to false and dispose this dialog
            terminateAcc = false;
            this.dispose();
            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
        //When okay button is pushed check if password is correct AND that they match
        try{
            if(passwordMatch == true){
                if(passwordEntered.equals(rs.getString("password"))){
                    terminateAcc = true;
                    rs.close();
                    stmt.close();
                    this.dispose();
                }
                else{
                    terminateAcc = false;
                    JOptionPane.showMessageDialog(this, "Incorrect Password entered.");
                }
            }
            else
                JOptionPane.showMessageDialog(this, "The passwords entered do not match, please double-check spelling");
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnOkayActionPerformed

    private void confirmPassFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPassFieldKeyReleased
        //get the charArray entered in both password fields
        passwordEntered = String.valueOf(passField.getPassword());
        confirmedPassword = String.valueOf(confirmPassField.getPassword());
        
        //check if they match
        if(confirmedPassword.equals(passwordEntered)){
            passwordMatch = true;
        }
        else
            passwordMatch = false;
    }//GEN-LAST:event_confirmPassFieldKeyReleased

    private void passFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyReleased
        passwordEntered = String.valueOf(passField.getPassword());
        confirmedPassword = String.valueOf(confirmPassField.getPassword());
        
        //check if they match
        if(confirmedPassword.equals(passwordEntered)){
            passwordMatch = true;
        }
        else
            passwordMatch = false;
    }//GEN-LAST:event_passFieldKeyReleased

    private void passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusGained
        //When focused, clear pre-written text
        if(String.valueOf(passField.getPassword()).equals("aaaaaaaaaaaaaaa"))
            passField.setText("");
    }//GEN-LAST:event_passFieldFocusGained

    private void confirmPassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFieldFocusGained
        //when focused clear pre-written text
        if(String.valueOf(confirmPassField.getPassword()).equals("aaaaaaaaaaaaaaa"))
            confirmPassField.setText("");
    }//GEN-LAST:event_confirmPassFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Terminate dialog = new Terminate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOkay;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passField;
    // End of variables declaration//GEN-END:variables
}
